version: "3"
services:
  nginx:
    image: nginx:latest
  httpd:
    image: httpd:latest
  envoy:
    image: envoyproxy/envoy:v1.14-latest
    ports:
      - 80:80
    volumes:
      - ${PWD}/etc/envoy:/etc/envoy
